apiVersion: apps/v1
kind: Deployment
metadata:
  name: legalview-blue
  namespace: prod
  labels:
    app: legalview
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legalview
      color: blue
  template:
    metadata:
      labels:
        app: legalview
        color: blue
    spec:
      containers:
        - name: legalview
          image: REPLACEME_IMAGE:REPLACEME_TAG
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
