apiVersion: v1
kind: Service
metadata:
  name: legalview-metrics
  namespace: prod
  labels:
    app: legalview
    monitoring: metrics
spec:
  selector:
    app: legalview
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: legalview
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: legalview
      monitoring: metrics
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
