apiVersion: v1
kind: Service
metadata:
  name: legalview
  namespace: prod
spec:
  selector:
    app: legalview
    color: blue
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
